CREATE DATABASE IF NOT EXISTS K4;

USE K4;

CREATE TABLE IF NOT EXISTS table_mhs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nama VARCHAR(100) NOT NULL,
    NIM VARCHAR(20) NOT NULL,
    Universitas VARCHAR(100) NOT NULL,
    Fakultas VARCHAR(50) NOT NULL,
    Jurusan VARCHAR(50) NOT NULL,
    Peminatan VARCHAR(50) NOT NULL,
    Alamat VARCHAR(255) NOT NULL,
    Phone VARCHAR(20) NOT NULL
);
